### ISSUE TITLE
dpl fails with `system': wrong first argument (ArgumentError)

### ISSUE THREAD

**Issue by takn** [travis-ci/dpl#1010]
yml:

```
deploy:
  - provider: script
    skip_cleanup: false
    script: 
      - echo 'about to call publish-edge**************'
      - pwd
      - ./scripts/publish-edge.sh
    on:
      all_branches: true
```

error:

```
1.55s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching dpl-1.10.11.gem
Successfully installed dpl-1.10.11
Parsing documentation for dpl-1.10.11
Installing ri documentation for dpl-1.10.11
Done installing documentation for dpl after 0 seconds
1 gem installed
dpl.1
Installing deploy dependencies
Fetching dpl-script-1.10.11.gem
Successfully installed dpl-script-1.10.11
Parsing documentation for dpl-script-1.10.11
Installing ri documentation for dpl-script-1.10.11
Done installing documentation for dpl-script after 0 seconds
1 gem installed
dpl.2
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): d102a8f remove skip cleanup
dpl.3
Deploying application
Already up to date!
HEAD detached at d102a8f
nothing to commit, working tree clean
Dropped refs/stash@{0} (29de33209bb48ce945280b5953cd2c6d430770db)
/home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/cli.rb:54:in `system': wrong first argument (ArgumentError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/cli.rb:54:in `shell'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-script-1.10.11/lib/dpl/provider/script.rb:19:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.11/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
`script` needs to be a single string value. https://docs.travis-ci.com/user/deployment/script

**Comment by takn** [comment]
thank you!
