### ISSUE TITLE
[provider: pypi] fails to install correct dependency

### ISSUE THREAD

**Issue by chungg** [travis-ci/dpl#1022]
we get the following when trying to deploy:

```
running egg_info
creating gnocchi.egg-info
writing requirements to gnocchi.egg-info/requires.txt
writing gnocchi.egg-info/PKG-INFO
writing top-level names to gnocchi.egg-info/top_level.txt
writing dependency_links to gnocchi.egg-info/dependency_links.txt
writing entry points to gnocchi.egg-info/entry_points.txt
writing manifest file 'gnocchi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.github'
writing manifest file 'gnocchi.egg-info/SOURCES.txt'
running check
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    cmdclass=cmdclass,
  File "/home/travis/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/.local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 52, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
    klass = self.get_command_class(command)
  File "/home/travis/.local/lib/python2.7/site-packages/setuptools/dist.py", line 837, in get_command_class
    ep.require(installer=self.fetch_build_egg)
  File "/home/travis/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9.0'), set(['bleach']))
Traceback (most recent call last):
  File "/home/travis/.local/bin/twine", line 10, in <module>
    sys.exit(main())
  File "/home/travis/.local/lib/python2.7/site-packages/twine/__main__.py", line 28, in main
    return dispatch(sys.argv[1:])
  File "/home/travis/.local/lib/python2.7/site-packages/twine/cli.py", line 75, in dispatch
    main = registered_commands[args.command].load()
  File "/home/travis/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9.0'), set(['bleach']))
```
for some reason it's not updating the dependencies when dpl installs `twine`. for reference, the yaml file is: https://github.com/gnocchixyz/gnocchi/blob/stable/4.3/.travis.yml

not sure if this is because we're using `language: generic` but our current workaround was to upgrade `six` explicitly in `before_deploy` stage. creating this issue in case there is a more appropriate fix/solution.

**Comment by svenfuchs** [comment]
@chungg i believe i've seen this error while working on dpl v2. would you be able to test this against the current edge version?

you can do so by adding the following to https://github.com/gnocchixyz/gnocchi/blob/stable/4.3/.travis.yml#L72

```
deploy:
  provider: pypi
  edge: true
```

i am going to assume this is fixed in dpl v2 and close this issue here. please do re-open and report back if this does not work for you. thank you!
