### ISSUE TITLE
DPL::Provider::Herkoku vs Heroku

### ISSUE THREAD

**Issue by chakeresa** [travis-ci/dpl#1078]
Trying to deploy my Express app to Heroku using Travis CI. It worked fine yesterday, but today I'm getting this error:
```
Installing deploy dependencies

/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:97:in `rescue in block in new': uninitialized constant DPL::Provider::Herkoku (NameError)
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
failed to deploy
```
Note that it says `Herkoku` instead of `Heroku`.

**Comment by chakeresa** [comment]
Found the typo in my `.travis.yml` file.
