### ISSUE TITLE
There was an error while trying to load the gem 'octokit'.

### ISSUE THREAD

**Issue by bundabrg** [travis-ci/dpl#1146]
Looks like another error like that seen in #1108. Build from today gives me this error

```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem uninstall -aIx dpl
Gem 'dpl' is not installed
1.43s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl --pre
Successfully installed regstry-1.0.14
Successfully installed cl-1.1.5
Successfully installed dpl-2.0.0.alpha.11
3 gems installed
Support for deployments to GitHub Pages is in **beta**. Please see [Maturity Levels](https://github.com/travis-ci/dpl/#maturity-levels) for details.
dpl.1
3.00sInstall deployment dependencies
Installing deployment dependencies
Installing gem dependencies: octokit (~> 4.14.0), public_suffix (~> 3.0.3)
There was an error while trying to load the gem 'octokit'.
Gem Load Error is: uninitialized constant Faraday::Error::ClientError
Did you mean?  Faraday::ClientError
Backtrace for gem load error is:
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `require'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit.rb:4:in `require'
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/inline.rb:70:in `gemfile'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:178:in `block in gems_require'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:172:in `chdir'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:172:in `gems_require'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:106:in `install_deps'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:251:in `before_install'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:226:in `block in run_stage'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:33:in `block in fold'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:48:in `time'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/ctx/bash.rb:31:in `fold'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:410:in `fold'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:225:in `run_stage'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:196:in `block in run'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:196:in `each'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/provider.rb:196:in `run'
/home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.1.5/lib/cl/runner/default.rb:23:in `run'
/home/travis/.rvm/gems/ruby-2.4.5/gems/cl-1.1.5/lib/cl.rb:32:in `run'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/lib/dpl/cli.rb:11:in `run'
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-2.0.0.alpha.11/bin/dpl:9:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
/home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
failed to deploy
```

[.travis.yml](https://github.com/bundabrg/BetonQuest/blob/607724f70b5a0ef9a4555b9cdddfde05519667bc/.travis.yml)

[Project Branch](https://github.com/bundabrg/BetonQuest/tree/607724f70b5a0ef9a4555b9cdddfde05519667bc)

**Comment by frzb** [comment]
Similar looking problem here: 

https://travis-ci.com/frzb/coinboot/jobs/271538927?utm_medium=notification&utm_source=email

https://raw.githubusercontent.com/frzb/coinboot/34e089ec43fad12a11765856b12c9485f1ef6d78/.travis.yml

**Comment by crazy-max** [comment]
Same for me https://travis-ci.com/portapps/wire-portable/builds/143011017 :(

**Comment by Kristinita** [comment]
Same for me — **<https://travis-ci.org/Kristinita/KristinitaPelican/jobs/632385821#L2230-L2283>**.

Thanks.

**Comment by proddy** [comment]
Same here with dpl to Github Releases - https://travis-ci.com/proddy/EMS-ESP/jobs/272709283

It's a problem with DPL version 2 (using `edge:`). Works fine for me if I go back to version 1. But I need the functionality it v2.

**Comment by frzb** [comment]
The work arround by @geniiii  https://github.com/3DStris/3DStris/commit/1b02140783aef2d347957c9ecaa2acafd01062dc did it for me.

**Comment by proddy** [comment]
yup, that fix works for me too. Many thanks @frzb for pointing it out and of course geniii for providing the workaround.

**Comment by Kristinita** [comment]
**Status: ✔️ Fixed for me**

[**Here**](https://travis-ci.org/Kristinita/KristinitaPelican/jobs/632385821#L2325) I clicked to `Restart job` (and nothing else)  → build status was changed from `Error` to `Passed`.

Thanks.

**Comment by frzb** [comment]
Thanks to @BanzaiMan for merging the fix https://github.com/travis-ci/dpl/commit/691cc0d2ba7c99085a4182668459171b5064eb19

Works for me and I could revert the work around.
