### ISSUE TITLE
Deployment failed for beanstalk

### ISSUE THREAD

**Issue by Sytten** [travis-ci/dpl#1171]
Hi! Since the new version of DPL (1.10.15), our deployment to beanstalk fail.
Here is the error message:
```
Run dpl --provider=elasticbeanstalk --access-key-id=*** --secret-access-key=*** --region=$EB_REGION --app=$EB_APP --bucket_name=$S3_BUCKET_NAME --bucket_path=$EB_BUCKET --env=staging
Installing deploy dependencies
Successfully installed jmespath-1.4.0
Successfully installed aws-eventstream-1.0.3
Successfully installed aws-sigv4-1.1.0
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-core-2.11.451
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-resources-2.11.451
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-2.11.451
Successfully installed rubyzip-1.3.0
Successfully installed dpl-elastic_beanstalk-1.10.15
8 gems installed

!!! AWS Elastic Beanstalk support is experimental !!!

Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
No local changes to save
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Deploying application
No stash entries found.
/usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/util.rb:25:in `encode': "\\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/util.rb:25:in `uri_escape'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param.rb:38:in `escape'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param.rb:20:in `to_s'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param_list.rb:52:in `map'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param_list.rb:52:in `to_s'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param_list.rb:66:in `initialize'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param_list.rb:57:in `new'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/param_list.rb:57:in `to_io'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/handler.rb:44:in `build_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/query/handler.rb:26:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.11.451/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
 	from /usr/local/bundle/gems/dpl-elastic_beanstalk-1.10.15/lib/dpl/provider/elastic_beanstalk.rb:148:in `create_app_version'
	from /usr/local/bundle/gems/dpl-elastic_beanstalk-1.10.15/lib/dpl/provider/elastic_beanstalk.rb:51:in `push_app'
	from /usr/local/bundle/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `block in deploy'
	from /usr/local/bundle/gems/dpl-1.10.15/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `deploy'
	from /usr/local/bundle/gems/dpl-1.10.15/lib/dpl/cli.rb:32:in `run'
	from /usr/local/bundle/gems/dpl-1.10.15/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.10.15/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
##[error]Process completed with exit code 1.
```

**Comment by svenfuchs** [comment]
Thanks for the report @Sytten. It looks like something may have changed in the AWS SDK used there. I'll have a look.

We generally recommend moving over to using `dpl v2`, which soon will become the default version. I am not aware of such issues in `v2`. 

If you are seeing this on Travis CI then you can opt into `v2` using:

```
deploy:
  - provider: elasticbeanstalk
    edge: true
    ...
```

See https://docs.travis-ci.com/user/deployment-v2/providers/elasticbeanstalk/ and https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release

**Comment by alexjurkiewicz** [comment]
Is there an unusual character in the git commit message?

**Comment by Sytten** [comment]
No we only use basic English in our commits. I will take a look at dpl v2 when I have the time.
