### ISSUE TITLE
Old AWS SDK

### ISSUE THREAD

**Issue by garbados** [travis-ci/dpl#1193]
Hello,

I encountered an issue that seems to stem from dpl using an outdated version of the AWS SDK. Here is a trace from a failed build:

```
Installing deploy dependencies
Successfully installed jmespath-1.4.0
Successfully installed aws-eventstream-1.1.0
Successfully installed aws-sigv4-1.1.3
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-core-2.11.507
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-resources-2.11.507
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
Successfully installed aws-sdk-2.11.507
Successfully installed mime-types-data-3.2020.0512
Successfully installed mime-types-3.3.1
Successfully installed dpl-s3-1.10.15

9 gems installed

NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3

Logging in with Access Key: ********************

/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.15/lib/dpl/provider/s3.rb:71:in `chdir': No such file or directory @ dir_chdir - build (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.15/lib/dpl/provider/s3.rb:71:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.15/lib/dpl/provider/s3.rb:124:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.15/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
I don't think the failure comes from the old library version. Those should be just warnings. 

The actual failure comes from
https://github.com/travis-ci/dpl/blob/v1.10.15/lib/dpl/provider/s3.rb#L71
which means that your `local_dir` value is incorrect. (It's either pointing to a wrong directory, or if it is generated during the build, you have not specified `skip_cleanup` option.)
