### ISSUE TITLE
No such file or directory or hostname error

### ISSUE THREAD

**Issue by WhyNotHugo** [travis-ci/dpl#1197]
Trying to make a manual release using `dpl` locally:

```console
$ dpl --provider=releases --username=whynothugo --repo=pimutils/vdirsyncer --file="dist/*"
Traceback (most recent call last):
	10: from /home/hugo/.gem/ruby/2.7.0/bin/dpl:23:in `<main>'
	 9: from /home/hugo/.gem/ruby/2.7.0/bin/dpl:23:in `load'
	 8: from /home/hugo/.gem/ruby/2.7.0/gems/dpl-2.0.0.beta.3/bin/dpl:9:in `<top (required)>'
	 7: from /home/hugo/.gem/ruby/2.7.0/gems/dpl-2.0.0.beta.3/lib/dpl/cli.rb:11:in `run'
	 6: from /home/hugo/.gem/ruby/2.7.0/gems/cl-1.2.4/lib/cl.rb:34:in `run'
	 5: from /home/hugo/.gem/ruby/2.7.0/gems/cl-1.2.4/lib/cl/runner/default.rb:26:in `run'
	 4: from /home/hugo/.gem/ruby/2.7.0/gems/cl-1.2.4/lib/cl/runner/default.rb:32:in `cmd'
	 3: from /home/hugo/.gem/ruby/2.7.0/gems/cl-1.2.4/lib/cl/runner/default.rb:32:in `new'
	 2: from /home/hugo/.gem/ruby/2.7.0/gems/dpl-2.0.0.beta.3/lib/dpl/provider.rb:195:in `initialize'
	 1: from /home/hugo/.gem/ruby/2.7.0/gems/dpl-2.0.0.beta.3/lib/dpl/ctx/bash.rb:458:in `machine_name'
/home/hugo/.gem/ruby/2.7.0/gems/dpl-2.0.0.beta.3/lib/dpl/ctx/bash.rb:458:in ``': No such file or directory - hostname (Errno::ENOENT)
```

I installed it using `gem install dpl --pre`.

Using `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`.

**Comment by WhyNotHugo** [comment]
Oh, looks like misread the message due to wrapping on my terminal.

Looks the script tries to use `hostname`, which isn't part of the base system on Linux. Maybe using `hostnamectl --static` would be best? That's part of systemd, so should be present on any system.

**Comment by WhyNotHugo** [comment]
Issue is still a problem.
