### ISSUE TITLE
uninitialized constant Rendezvous::StringIO

### ISSUE THREAD

**Issue by phortx** [travis-ci/dpl#1264]
```
-----> Launching...
 !     Release command declared: this new release will not be available until the command succeeds.
       Released v390
       [...] deployed to Heroku
/root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rendezvous-0.1.3/lib/rendezvous.rb:44:in `start': uninitialized constant Rendezvous::StringIO (NameError)
      if input.is_a?(StringIO)
                     ^^^^^^^^
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rendezvous-0.1.3/lib/rendezvous.rb:28:in `start'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-heroku-1.10.16/lib/dpl/provider/heroku/generic.rb:86:in `run'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/provider.rb:205:in `block (2 levels) in deploy'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/cli.rb:41:in `fold'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/provider.rb:205:in `block in deploy'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/provider.rb:201:in `each'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/provider.rb:201:in `deploy'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/cli.rb:32:in `run'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/lib/dpl/cli.rb:7:in `run'
	from /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/dpl-1.10.16/bin/dpl:5:in `<top (required)>'
	from /root/.asdf/installs/ruby/3.1.2/bin/dpl:25:in `load'
	from /root/.asdf/installs/ruby/3.1.2/bin/dpl:25:in `<main>'
```

Any idea?

**Comment by phortx** [comment]
I've worked around by adding

```Dockerfile
RUN sed -i '1s/^/require "stringio"\n/' /root/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rendezvous-0.1.3/lib/rendezvous.rb
````

to my GitLab CI Docker file which is used for the deployment. However, this feels really dirty :D

**Comment by ovidiuanca** [comment]
Had the same issue and fixed it after installing gem `faraday` after installing `dpl`.

In Gitlab CI:
```
script:
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --run ...
```
