### ISSUE TITLE
Github Release Failing

### ISSUE THREAD

**Issue by ritwikd** [travis-ci/dpl#162]
Hello, 

When I try to deploy a GitHub release, I get the below error. I get this even after I have tagged the commit. Here is a link to the most recent failed build: https://travis-ci.org/ritwikd/gt-dashboard/builds/31466448.

Thank you,
Ritwik Dutta

```
Preparing deploy
Logged in as Ritwik Dutta
Deploying to repo: ritwikd/gt-dashboard
Current tag is: 
dpl.3
Deploying application
/home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/ritwikd/gt-dashboard/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: missing_field
  field: tag_name
  resource: Release
  code: custom
  field: tag_name
  message: tag_name is not well-formed
  resource: Release
  code: custom
  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/sawyer-0.5.4/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.2.0/lib/octokit/client.rb:338:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.2.0/lib/octokit/client.rb:144:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.2.0/lib/octokit/client/releases.rb:32:in `create_release'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/provider/releases.rb:74:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/provider.rb:106:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/provider.rb:106:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.5/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by rene-dev** [comment]
for some reason Im still getting this: https://travis-ci.org/rene-dev/stmbl/builds/94665169

**Comment by BanzaiMan** [comment]
@rene-dev 
GitHub Releases is meant to work with tagged build, but yours is not. Tag a commit, then push it with `git push origin master --tags`.

Please consult https://docs.travis-ci.com/user/deployment/releases for further help.
