### ISSUE TITLE
error deploying to elastic beanstalk

### ISSUE THREAD

**Issue by dvschramm** [travis-ci/dpl#173]
config

```
language: node_js
node_js:
- 0.1
script: npm test
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  app: "PJS Services"
  env: "pjs-production"
  region: "us-east-1"
  access_key_id:
    secure: <key>
  secret_access_key:
    secure: <key>
  skip_cleanup: true

```

error https://travis-ci.org/p-js/services/builds/34877141

```
Fetching: dpl-1.6.6.gem (100%)
Successfully installed dpl-1.6.6
1 gem installed
dpl.1
Installing deploy dependencies
!!! AWS Elastic Beanstalk support is experimental !!!
Fetching: mini_portile-0.6.0.gem (100%)
Successfully installed mini_portile-0.6.0
Fetching: nokogiri-1.6.3.1.gem (100%)
Building native extensions.  This could take a while...
Building nokogiri using packaged libraries.
Building libxml2-2.8.0 for nokogiri with the following patches applied:
    - 0001-Fix-parser-local-buffers-size-problems.patch
    - 0002-Fix-entities-local-buffers-size-problems.patch
    - 0003-Fix-an-error-in-previous-commit.patch
    - 0004-Fix-potential-out-of-bound-access.patch
    - 0005-Detect-excessive-entities-expansion-upon-replacement.patch
    - 0006-Do-not-fetch-external-parsed-entities.patch
    - 0007-Enforce-XML_PARSER_EOF-state-handling-through-the-pa.patch
    - 0008-Improve-handling-of-xmlStopParser.patch
    - 0009-Fix-a-couple-of-return-without-value.patch
    - 0010-Keep-non-significant-blanks-node-in-HTML-parser.patch
    - 0011-Do-not-fetch-external-parameter-entities.patch
************************************************************************
IMPORTANT!  Nokogiri builds and uses a packaged version of libxml2.
If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall nokogiri as
follows:
    gem install nokogiri -- --use-system-libraries
If you are using Bundler, tell it to use the option:
    bundle config build.nokogiri --use-system-libraries
    bundle install
However, note that nokogiri does not necessarily support all versions
of libxml2.
For example, libxml2-2.9.0 and higher are currently known to be broken
and thus unsupported by nokogiri, due to compatibility problems and
XPath optimization bugs.
************************************************************************
Building libxslt-1.1.28 for nokogiri with the following patches applied:
    - 0001-Adding-doc-update-related-to-1.1.28.patch
    - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
    - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
    - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
    - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
    - 0007-Separate-function-for-predicate-matching-in-patterns.patch
    - 0008-Fix-direct-pattern-matching.patch
    - 0009-Fix-certain-patterns-with-predicates.patch
    - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
    - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
    - 0014-Fix-for-bug-436589.patch
    - 0015-Fix-mkdir-for-mingw.patch
************************************************************************
IMPORTANT!  Nokogiri builds and uses a packaged version of libxslt.
If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall nokogiri as
follows:
    gem install nokogiri -- --use-system-libraries
If you are using Bundler, tell it to use the option:
    bundle config build.nokogiri --use-system-libraries
    bundle install
************************************************************************
Successfully installed nokogiri-1.6.3.1
Fetching: aws-sdk-v1-1.52.0.gem (100%)
Successfully installed aws-sdk-v1-1.52.0
Fetching: aws-sdk-1.52.0.gem (100%)
Successfully installed aws-sdk-1.52.0
4 gems installed
Fetching: rubyzip-1.1.6.gem (100%)
Successfully installed rubyzip-1.1.6
1 gem installed
dpl.2
Preparing deploy
dpl.3
Deploying application
/home/travis/.rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-v1-1.52.0/lib/aws/core/client.rb:375:in `return_or_raise': The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again. (AWS::S3::Errors::BucketAlreadyExists)
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-v1-1.52.0/lib/aws/core/client.rb:476:in `client_request'
    from (eval):3:in `create_bucket'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-v1-1.52.0/lib/aws/s3/bucket_collection.rb:109:in `create'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider/elastic_beanstalk.rb:70:in `create_bucket'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider/elastic_beanstalk.rb:23:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider.rb:108:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider.rb:108:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
Is there anything left to do on this?

**Comment by nesQuick** [comment]
@BanzaiMan I think everything I mentioned before is covered in #273

**Comment by BigChief45** [comment]
@BanzaiMan I think this issue can be closed now.
