### ISSUE TITLE
Github release fails with zip randomly

### ISSUE THREAD

**Issue by ogirardot** [travis-ci/dpl#174]
I create a zip after a build and intend to put it into the release but, it ends up sometime with : 

```
/home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/*****<my repo>/releases/549254/assets?name=release.zip: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: ReleaseAsset
  code: custom
  field: size
  message: size is not included in the list // See: https://developer.github.com/v3
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/octokit-3.3.1/lib/octokit/client/releases.rb:94:in `upload_asset'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider/releases.rb:108:in `block in push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider/releases.rb:92:in `each'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider/releases.rb:92:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider.rb:108:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/provider.rb:108:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/gems/dpl-1.6.6/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p547/bin/dpl:23:in `<main>'
failed to deploy
```

Does that ring any bell ? this is kinda blocker for me...

Regards, 
Olivier.

**Comment by nichtich** [comment]
This feature has not been documented yet

**Comment by BanzaiMan** [comment]
Is this still an issue?

**Comment by prashantfoodpanda** [comment]
Please check api-key
