### ISSUE TITLE
error with divshot depoy

### ISSUE THREAD

**Issue by djindjic** [travis-ci/dpl#216]
[here](https://travis-ci.org/djindjic/fatburnhub/builds/47560381#L386) is my log and at line 386 says:
```bach
npm ERR! fetch failed https://registry.npmjs.org/reverend/-/reverend-0.2.0.tgz
npm ERR! Error: 400 Bad Request
npm ERR!     at WriteStream.<anonymous> (/home/travis/.nvm/v0.10.35/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at /home/travis/.nvm/v0.10.35/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 2.6.32-042stab090.5
npm ERR! command "/home/travis/.nvm/v0.10.35/bin/node" "/home/travis/.nvm/v0.10.35/bin/npm" "install" "-g" "divshot-cli"
npm ERR! cwd /home/travis/build/djindjic/fatburnhub
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by djindjic** [comment]
just to notice that this issue simply works now. tnx
