### ISSUE TITLE
Some problem for upload a release to github with GitHub Two Factor Authentication

### ISSUE THREAD

**Issue by Xuanwo** [travis-ci/dpl#270]
```
For accounts using two factor authentication, you have to use an oauth token as a username and password will not work.
```
what does it mean? Should I use the token as 'User'?

I use the `travis setup release` to create the token, and my yml looks like that:
```
deploy:
  provider: releases
  api_key:
    secure: xxxxxxxx
  file: xxx.xxx
  skip_cleanup: true
  on:
    repo: xxxxxx
```

however, I always meet the 401 error, looks like that:
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client.rb:339:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client.rb:135:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:43:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:68:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:72:in `check_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:122:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:121:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

what should I do?

Thanks for all the help.

**Comment by BanzaiMan** [comment]
Does the token have the correct scope? http://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-Oauth-token

**Comment by Xuanwo** [comment]
Yes.
![image](https://cloud.githubusercontent.com/assets/5351546/7950796/73418d96-09d2-11e5-88d9-28a29baf94e9.png)

**Comment by BanzaiMan** [comment]
Could you email support@travis-ci.com along with the build log URL which exhibits this problem? Thanks.

**Comment by Xuanwo** [comment]
OK, I will.
Thank you for your advice.

**Comment by Xuanwo** [comment]
Well, sloved.
It seems like something wrong in the database of Travis-CI, a friend in travis help me reset the repo, the problem solved.
so, if have the same problem, please email the support~

Close this issue.
