### ISSUE TITLE
Elastic beanstalk

### ISSUE THREAD

**Issue by keithamus** [travis-ci/dpl#278]
I'm trying to get an app deployed to elastic beanstalk using dpl, and I'm getting the following error:

```bash
$ cat deploy.sh
#!/bin/sh
dpl \
  --provider=elasticbeanstalk \
  --access-key-id=<snip> \
  --secret-access-key="<snip>" \
  --app="test-app" \
  --env="production" \
  --region="us-east-1" \
  --bucket_name="elasticbeanstalk-us-east-1-<snip>" \
  --skin_cleanup="true" \
  --edge="true" \

$ ./deploy.sh
Installing deploy dependencies

!!! AWS Elastic Beanstalk support is experimental !!!

Preparing deploy
Saved working directory and index state WIP on master: 3dda7ef Ensure cleanup is skipped
HEAD is now at 3dda7ef Ensure cleanup is skipped
Deploying application
On branch master
Your branch is up-to-date with 'origin/master'.
/Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:375:in `return_or_raise': Access Denied (AWS::S3::Errors::AccessDenied)
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `list_buckets'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-v1-1.64.0/lib/aws/s3/bucket_collection.rb:140:in `each'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/provider/elastic_beanstalk.rb:76:in `map'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/provider/elastic_beanstalk.rb:76:in `bucket_exists?'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/provider/elastic_beanstalk.rb:23:in `push_app'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/provider.rb:137:in `block in deploy'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/cli.rb:41:in `fold'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/provider.rb:137:in `deploy'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/cli.rb:32:in `run'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/lib/dpl/cli.rb:7:in `run'
	from /Users/<snip>/.rvm/gems/ruby-2.0.0-p247/gems/dpl-1.7.12/bin/dpl:5:in `<top (required)>'
	from /Users/<snip>/.rvm/rubies/ruby-2.0.0-p247/bin/dpl:23:in `load'
	from /Users/<snip>/.rvm/rubies/ruby-2.0.0-p247/bin/dpl:23:in `<main>'
```

As far as I can tell this is suggesting that the iam user does not have permission to list buckets, but it does - here are the policy files it has:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "elasticbeanstalk:CreateApplicationVersion",
                "elasticbeanstalk:DescribeEnvironments",
                "elasticbeanstalk:DeleteApplicationVersion",
                "elasticbeanstalk:UpdateEnvironment"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "sns:CreateTopic",
                "sns:GetTopicAttributes",
                "sns:ListSubscriptionsByTopic",
                "sns:Subscribe"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:sns:us-east-1:<snip>:*"
        },
        {
            "Action": [
                "autoscaling:SuspendProcesses",
                "autoscaling:DescribeScalingActivities",
                "autoscaling:ResumeProcesses",
                "autoscaling:DescribeAutoScalingGroups"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "cloudformation:GetTemplate",
                "cloudformation:DescribeStackResource",
                "cloudformation:UpdateStack"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:cloudformation:us-east-1:<snip>:*"
        },
        {
            "Action": [
                "ec2:DescribeImages",
                "ec2:DescribeKeyPairs"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:GetBucketPolicy"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::elasticbeanstalk-us-east-1-<snip>",
                "arn:aws:s3:::elasticbeanstalk-us-east-1-<snip>/*"
            ]
        },
        {
            "Action": [
                "elasticloadbalancing:DescribeInstanceHealth",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

Most notably, `"s3:ListBucket"` is present.

Is this an error with my policy config, or with the elasticbeanstalk strategy?

**Comment by thiagomurakami** [comment]
@keithamus @BanzaiMan Since this question is quite old, I don't know if this will still help, but I talked to AWS' support and the action is
```s3:ListAllMyBuckets```
And all ``List``, ``Head`` and ``Describe`` actions need ``Resource: *``.

Hope this helps, cheers.

**Comment by BigChief45** [comment]
@BanzaiMan Seems this issue can be closed now.
