### ISSUE TITLE
PyPi deployments fail when deploy is not in the right directory

### ISSUE THREAD

**Issue by adiroiban** [travis-ci/dpl#355]
I have this build

https://travis-ci.org/twisted/twistedchecker/builds/86362597

and it fails to deploy with 

```
Fetching: dpl-1.8.6.gem (100%)
Successfully installed dpl-1.8.6
1 gem installed
dpl.1
Installing deploy dependencies
--2015-10-20 09:47:34--  https://bootstrap.pypa.io/ez_setup.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 23.235.39.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|23.235.39.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11432 (11K) [text/x-python]
Saving to: `STDOUT'
100%[======================================>] 11,432      --.-K/s   in 0s      
2015-10-20 09:47:34 (733 MB/s) - written to stdout [11432/11432]
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.4.zip
Extracting in /tmp/tmpqGCwdR
Now working in /tmp/tmpqGCwdR/setuptools-18.4
Installing Setuptools
running install
running bdist_egg
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying easy_install.py -> build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pkg_resources
copying pkg_resources/__init__.py -> build/lib.linux-x86_64-2.7/pkg_resources
creating build/lib.linux-x86_64-2.7/setuptools
copying setuptools/py26compat.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/sandbox.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/extension.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/archive_util.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/lib2to3_ex.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/utils.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/__init__.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/msvc9_support.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/unicode_utils.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/py27compat.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/package_index.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/ssl_support.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/py31compat.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/dist.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/depends.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/site-patch.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/windows_support.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/version.py -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/compat.py -> build/lib.linux-x86_64-2.7/setuptools
creating build/lib.linux-x86_64-2.7/_markerlib
copying _markerlib/markers.py -> build/lib.linux-x86_64-2.7/_markerlib
copying _markerlib/__init__.py -> build/lib.linux-x86_64-2.7/_markerlib
creating build/lib.linux-x86_64-2.7/pkg_resources/_vendor
copying pkg_resources/_vendor/__init__.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor
creating build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/__init__.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/specifiers.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_compat.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/__about__.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/version.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_structures.py -> build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging
creating build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/saveopts.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/install_scripts.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/develop.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/build_py.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/__init__.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/install.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/install_lib.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/register.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/bdist_wininst.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/egg_info.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/install_egg_info.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/build_ext.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/test.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/bdist_rpm.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/bdist_egg.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/setopt.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/easy_install.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/rotate.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/sdist.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/upload_docs.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/command/alias.py -> build/lib.linux-x86_64-2.7/setuptools/command
copying setuptools/script (dev).tmpl -> build/lib.linux-x86_64-2.7/setuptools
copying setuptools/script.tmpl -> build/lib.linux-x86_64-2.7/setuptools
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pkg_resources
copying build/lib.linux-x86_64-2.7/pkg_resources/__init__.py -> build/bdist.linux-x86_64/egg/pkg_resources
creating build/bdist.linux-x86_64/egg/pkg_resources/_vendor
creating build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/__init__.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/specifiers.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/_compat.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/__about__.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/version.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/packaging/_structures.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging
copying build/lib.linux-x86_64-2.7/pkg_resources/_vendor/__init__.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor
creating build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/py26compat.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/sandbox.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/extension.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/archive_util.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/lib2to3_ex.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/utils.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/__init__.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/msvc9_support.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/unicode_utils.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/py27compat.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/package_index.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/ssl_support.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/py31compat.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/dist.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/script (dev).tmpl -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/depends.py -> build/bdist.linux-x86_64/egg/setuptools
creating build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/saveopts.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/install_scripts.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/develop.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/build_py.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/__init__.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/install.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/install_lib.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/register.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/bdist_wininst.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/egg_info.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/install_egg_info.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/build_ext.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/test.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/bdist_rpm.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/bdist_egg.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/setopt.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/easy_install.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/rotate.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/sdist.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/upload_docs.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/command/alias.py -> build/bdist.linux-x86_64/egg/setuptools/command
copying build/lib.linux-x86_64-2.7/setuptools/site-patch.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/windows_support.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/version.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/compat.py -> build/bdist.linux-x86_64/egg/setuptools
copying build/lib.linux-x86_64-2.7/setuptools/script.tmpl -> build/bdist.linux-x86_64/egg/setuptools
creating build/bdist.linux-x86_64/egg/_markerlib
copying build/lib.linux-x86_64-2.7/_markerlib/markers.py -> build/bdist.linux-x86_64/egg/_markerlib
copying build/lib.linux-x86_64-2.7/_markerlib/__init__.py -> build/bdist.linux-x86_64/egg/_markerlib
copying build/lib.linux-x86_64-2.7/easy_install.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/specifiers.py to specifiers.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/_compat.py to _compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/__about__.py to __about__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/packaging/_structures.py to _structures.pyc
byte-compiling build/bdist.linux-x86_64/egg/pkg_resources/_vendor/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/py26compat.py to py26compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/sandbox.py to sandbox.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/extension.py to extension.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/archive_util.py to archive_util.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/lib2to3_ex.py to lib2to3_ex.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/msvc9_support.py to msvc9_support.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/unicode_utils.py to unicode_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/py27compat.py to py27compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/package_index.py to package_index.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/ssl_support.py to ssl_support.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/py31compat.py to py31compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/dist.py to dist.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/depends.py to depends.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/saveopts.py to saveopts.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/install_scripts.py to install_scripts.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/develop.py to develop.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/build_py.py to build_py.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/install.py to install.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/install_lib.py to install_lib.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/register.py to register.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/bdist_wininst.py to bdist_wininst.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py to egg_info.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/install_egg_info.py to install_egg_info.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py to build_ext.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/test.py to test.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/bdist_rpm.py to bdist_rpm.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py to bdist_egg.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/setopt.py to setopt.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py to easy_install.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/rotate.py to rotate.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/sdist.py to sdist.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/upload_docs.py to upload_docs.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/command/alias.py to alias.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/site-patch.py to site-patch.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/windows_support.py to windows_support.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/setuptools/compat.py to compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/_markerlib/markers.py to markers.pyc
byte-compiling build/bdist.linux-x86_64/egg/_markerlib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/easy_install.py to easy_install.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setuptools.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/setuptools-18.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing setuptools-18.4-py2.7.egg
Copying setuptools-18.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing setuptools 12.0.5 from easy-install.pth file
Adding setuptools 18.4 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin
Installed /usr/local/lib/python2.7/dist-packages/setuptools-18.4-py2.7.egg
Processing dependencies for setuptools==18.4
Finished processing dependencies for setuptools==18.4
rm: cannot remove `setuptools-18.4.zip': Permission denied
You are using pip version 6.0.7, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting twine
  Downloading twine-1.6.3-py2.py3-none-any.whl
Collecting pkginfo>=1.0 (from twine)
  Downloading pkginfo-1.2.1.tar.gz
Collecting requests>=2.3.0 (from twine)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |################################| 499kB 652kB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7.0 in /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages (from twine)
Collecting requests-toolbelt>=0.4.0 (from twine)
  Downloading requests_toolbelt-0.4.0-py2.py3-none-any.whl
Installing collected packages: requests-toolbelt, requests, pkginfo, twine
  Running setup.py install for pkginfo
    Installing pkginfo script to /home/travis/virtualenv/python2.7.9/bin
Successfully installed pkginfo-1.2.1 requests-2.8.1 requests-toolbelt-0.4.0 twine-1.6.3
error: could not lock config file .git/config: No such file or directory
error: could not lock config file .git/config: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - .dpl (Errno::EACCES)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `each'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider.rb:128:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
Hello. Your build is in a wrong directory when it tries to deploy: https://travis-ci.org/twisted/twistedchecker/builds/86362597#L619

Could you try moving back to `$TRAVIS_BUILD_DIR`?

**Comment by adiroiban** [comment]
after changing the directory in a before_deploy it works....

but I still think that the deploy command should be smart and auto change the directory

Thanks!

**Comment by BanzaiMan** [comment]
I see what you are saying, but users who do want the directories changed before the deployment and expects the build to be in that directory when the deployment starts will need to adjust their working configuration.

We might revisit the issue, but for now, I think it is best to not change this behavior.

I'm closing this.

**Comment by adiroiban** [comment]
Maybe the documentation from http://docs.travis-ci.com/user/deployment/pypi/ can be updated to have a warning that the dpl command must be executed from the $TRAVIS_BUILD_DIR

Thanks!
