### ISSUE TITLE
S3 deployment fails due to "mime-types" gem

### ISSUE THREAD

**Issue by joschi** [travis-ci/dpl#368]
The deployment to S3 after a successful build currently fails because the "mime-types" gem requires Ruby >= 2.0 but Ruby 1.9.3-p551 is installed by default:
```
Fetching: mime-types-data-3.2015.1120.gem (100%)
ERROR:  Error installing mime-types:
	mime-types-data requires Ruby version >= 2.0.
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mime-types (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:76:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:7:in `<class:S3>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:55:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```
https://travis-ci.org/Graylog2/graylog2-web-interface/jobs/92673328#L2993-L3009 (copy: https://gist.github.com/joschi/429cf43acfa04c2e53a2#file-log-txt-L6593-L6612)

**Comment by cotsog** [comment]
Hey @joschi,

Thank you for reporting this.

FYI it was also reported here: https://github.com/travis-ci/travis-ci/issues/5145 and it should have been fixed by https://github.com/travis-ci/dpl/pull/365 that was deployed earlier today.

Please re-open if it's not the case.

Thanks!

**Comment by joschi** [comment]
@cotsog Awesome. Thank you!
