### ISSUE TITLE
Cannot deploy cookbooks with issues_url in metadata

### ISSUE THREAD

**Issue by ephracis** [travis-ci/dpl#464]
When trying to deploy my cookbook to Chef Supermarket I get the following error:

```
/home/travis/build/simplare-cookbooks/no-ip/metadata.rb:8:in `from_file': undefined
method `issues_url' for #<Chef::Cookbook::Metadata:0x00000003578020> (NoMethodError)
```

It seems that Travis insists on using an old version of Chef that is not compatible with cookbooks developed for Chef 12. The code suggests that this is to stay compatible with Ruby 1.9, which has been unsupported since 2014.

I suggest you either bump up Chef to at least version 12, or make it possible to manually specify the desired version in `.travis.yml`.

**Comment by dcparker88** [comment]
I ran in to this issue today. The only workaround I can see is to remove `issues_url` and `source_url` from my metadata.rb. Did you discover a better workaround?

**Comment by BanzaiMan** [comment]
Could you try the `ruby-2.3` branch, assuming that you are running your build on Trusty?

```yaml
dist: trusty
⋮
deploy:
  on:
    edge:
      branch: ruby-2.3
  provider: chef_supermarket
  ⋮ # rest
```

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/dpl/issues/513 for additional context.

**Comment by dcparker88** [comment]
didn't seem to work, still got the error:
`/home/travis/build/target/dse-cookbook/metadata.rb:8:in `from_file': undefined method `source_url' for #<Chef::Cookbook::Metadata:0x00000001237c28> (NoMethodError)`

The file I changed is here: https://github.com/target/dse-cookbook/blob/55fe74014764bc07b94278b2a70d5e06ab45328b/.travis.yml

It does look like it ran the latest version, as it's giving me some more warnings for deprecations, but the actual upload to supermarket still fails.

**Comment by BanzaiMan** [comment]
@dcparker88 Thanks for trying, but could you post the build log URL instead?

**Comment by BanzaiMan** [comment]
@dcparker88 I see that there was a mistake in my earlier comment. I fixed it now (above). Could you try it again? https://github.com/target/dse-cookbook/blob/55fe74014764bc07b94278b2a70d5e06ab45328b/.travis.yml#L13-L15

**Comment by dcparker88** [comment]
here's the log: https://api.travis-ci.org/jobs/269413431/log.txt?deansi=true

making sure I didn't miss anything in the above comments

**Comment by BanzaiMan** [comment]
@dcparker88 https://travis-ci.org/target/dse-cookbook/jobs/269413431 points to an incorrect configuration: https://github.com/target/dse-cookbook/blob/ed6ac4d894407e881e50fa544c571483a11f95a8/.travis.yml#L8-L12. Could you move `edge` up one level, so that it sits right under `deploy` (alongside `on`)?

**Comment by dcparker88** [comment]
🤦‍♂️ I'm struggling tonight: https://api.travis-ci.org/jobs/269418821/log.txt?deansi=true 
https://github.com/target/dse-cookbook/blob/master/.travis.yml#L8-L12

thanks for helping though :)

**Comment by BanzaiMan** [comment]
OK. Looks like our dependency resolution for `chef` 12.x is coming down to a version of `ohai` requiring Ruby 2.3. It is not clear to me how, though; `chef` by itself can be installed on Ruby 2.2.

The reason that we prefer Ruby 2.2 now is that it is available on the newer Trusty image. Maybe we can wait a little while longer and ensure 2.3 is available everywhere.

**Comment by dragonsmith** [comment]
Hello @BanzaiMan ,

Please let me bump this issue up.
Is there any news regarding ruby-2.3 or new base image?

I doubt ruby-2.3 would be released for trusty :)

I'm getting a similar error too:

```
ERROR:  Error installing chef:
	There are no versions of ohai (~> 13.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	ohai requires Ruby version >= 2.3. The current ruby version is 2.2.0.
Successfully installed ffi-1.9.18
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- chef (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider.rb:85:in `requires'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider/chef_supermarket.rb:10:in `<class:ChefSupermarket>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider/chef_supermarket.rb:3:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider/chef_supermarket.rb:2:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider/chef_supermarket.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider.rb:59:in `const_get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider.rb:59:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/provider.rb:56:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.31.1/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

.travis.yml configuration looks like that:

```
deploy:
  edge:
    branch: ruby-2.3
  provider: chef-supermarket
  user_id: dr_agon
  client_key: ".travis/dr_agon.pem"
  cookbook_category: Other
  skip_cleanup: true
  on:
    tags: true
```

I'm confused. If RVM is used already, why is there a problem to install ruby 2.3 before deploy and switch to it?

It is pretty obvious and straightforward solution.

Thank you very much!

**Comment by BanzaiMan** [comment]
> I'm confused. If RVM is used already, why is there a problem to install ruby 2.3 before deploy and switch to it?

Installing a Ruby runtime at deployment time adds seconds (a couple dozens, maybe?). If you want to do that, it is not impossible to do (though undocumented).

**Comment by trinitronx** [comment]
@ephracis :  Best way to make cookbook `metadata.rb` backwards compatible while still meeting the new Chef supermarket quality standards & passing new foodcritic "criticisms" is to use a conditional define to "guard"  old Chef versions against the undefined method error.  The reason this works is because all the new `source_url`, `issues_url`, `chef_version` metadata keywords are actually Ruby methods defined in the context that `metadata.rb` has in the [`Chef::Cookbook::Metadata` class][2].  

[For example][1]
```
source_url 'https://github.com/trinitronx/kodi-cookbook'  if respond_to?(:source_url)
issues_url 'https://github.com/trinitronx/kodi-cookbook/issues'   if respond_to?(:issues_url)

chef_version '>= 12.5.1' if respond_to?(:chef_version)
```

Although these `if respond_to?()` guards fix the method undefined error, you'll still probably get another error when TravisCI tries to deploy to supermarket, as in #9178.

[1]: https://github.com/trinitronx/kodi-cookbook/blob/080ec064e69ea7fc758c09281e1224fdbf8b8a40/metadata.rb#L9-L10
[2]: http://www.rubydoc.info/gems/chef/Chef/Cookbook/Metadata

**Comment by trinitronx** [comment]
I also tried the `deploy.edge.branch: ruby-2.3` setting and it looks like I get the same error about `ohai` gem and Ruby version:

```
Building dpl gem locally with source travis-ci/dpl and branch ruby-2.3
0.00s
0.70s$ git clone https://github.com/travis-ci/dpl travis-ci/dpl
Cloning into 'travis-ci/dpl'...
0.00s
0.01s$ git checkout ruby-2.3
Switched to a new branch 'ruby-2.3'
Branch 'ruby-2.3' set up to track remote branch 'ruby-2.3' from 'origin'.
0.01s$ git show-ref -s HEAD
e6a53d8f4cb4ce76b1ce3a301af348b3f8ee8547
1.12s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem build dpl.gemspec
WARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on rspec-its (>= 0, development) is not recommended
  if rspec-its is semantically versioned, use:
    add_development_dependency 'rspec-its', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on json (>= 0, development) is not recommended
  if json is semantically versioned, use:
    add_development_dependency 'json', '~> 0'
WARNING:  open-ended dependency on tins (>= 0, development) is not recommended
  if tins is semantically versioned, use:
    add_development_dependency 'tins', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: dpl
  Version: 1.8.42.travis.39.1
  File: dpl-1.8.42.travis.39.1.gem
0.01s
0.00s
0.01s
0.00s
0.00s
1.22s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install $TRAVIS_BUILD_DIR/dpl-*.gem --local --pre
Successfully installed dpl-1.8.42.travis.39.1
1 gem installed
dpl.1
Installing deploy dependencies
Successfully installed rack-2.0.4
1 gem installed
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
2 gems installed
Successfully installed mixlib-shellout-2.3.2
Successfully installed mixlib-config-2.2.5
Successfully installed fuzzyurl-0.9.0
Successfully installed public_suffix-3.0.1
Successfully installed addressable-2.5.2
Successfully installed tomlrb-1.2.6
Successfully installed chef-config-13.7.16
Successfully installed mixlib-cli-1.7.0
Successfully installed mixlib-log-1.7.1
Successfully installed mixlib-authentication-1.4.2
Successfully installed mixlib-archive-0.4.1
Successfully installed systemu-2.6.5
Building native extensions. This could take a while...
Successfully installed libyajl2-1.2.0
Building native extensions. This could take a while...
Successfully installed ffi-yajl-2.3.1
Successfully installed plist-3.4.0
Successfully installed ipaddress-0.8.3
Successfully installed wmi-lite-1.0.0
Building native extensions. This could take a while...
ERROR:  Error installing chef:
	There are no versions of ohai (~> 13.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	ohai requires Ruby version >= 2.3. The current ruby version is 2.2.0.
Successfully installed ffi-1.9.21
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- chef (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider.rb:85:in `requires'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider/chef_supermarket.rb:10:in `<class:ChefSupermarket>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider/chef_supermarket.rb:3:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider/chef_supermarket.rb:2:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider/chef_supermarket.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider.rb:59:in `const_get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider.rb:59:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/provider.rb:56:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42.travis.39.1/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
`dpl` 1.9.x is out. `chef` should now resolve to version 12 or 13.
