### ISSUE TITLE
AWS Elasticbeanstalk deployment to China

### ISSUE THREAD

**Issue by cameron-white-janrain** [travis-ci/dpl#497]
When running the following script:

```
sudo dpl \
    --provider=elasticbeanstalk \
    --access-key-id=$AWS_ACCESS_KEY --secret-access-key=$AWS_SECRET_ACCESS_KEY \
    --app=$APP \
    --env=$ENV \
    --zip_file=artifact.zip \ 
    --bucket_name=$BUCKET \
    --region=cn-north-1 \
     --skip_cleanup=true
```

I get the following:

```
Installing deploy dependencies

!!! AWS Elastic Beanstalk support is experimental !!!

Preparing deploy
Deploying application
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:857:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/connection_pool.rb:327:in `start_session'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/connection_pool.rb:127:in `session_for'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/net_http_handler.rb:56:in `handle'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:253:in `block in make_sync_request'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:289:in `retry_server_errors'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:249:in `make_sync_request'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:391:in `log_client_request'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:477:in `block in client_request'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:373:in `return_or_raise'
        from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
        from (eval):3:in `create_application_version'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/provider/elastic_beanstalk.rb:142:in `create_app_version'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/provider/elastic_beanstalk.rb:48:in `push_app'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `block in deploy'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `deploy'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
        from /usr/local/bin/dpl:23:in `load'
        from /usr/local/bin/dpl:23:in `<main>'
```

I think the problem might be that DPL does not know to look at the Chinese AWS Partition but I don't know for sure. Is there anyway to get this to work?

**Comment by BanzaiMan** [comment]
It appears to me that the issue is with the current implementation using SDK v1, which doesn't know anything about this region.
