### ISSUE TITLE
S3: The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by adriannewby-crownpeak** [travis-ci/dpl#515]
I have an odd situation.  I am running the exact same .travis.yml in two separate projects, except for the S3 bucket folder (not bucket, folder) they upload their build artifacts to.

In one project, the S3 transfer works fine.  In the other project I get the infamous signature error.

**This happens consistently.  One always succeeds.  One always fails.**

Here's the "good" .travis.yml:

~~~~
# Deploy artifacts to S3
deploy:
  provider: s3
  access_key_id: <snip/>
  secret_access_key:
    secure: <snip/>
  bucket: crownpeak-builds
  upload-dir: crownpeak-core
  storage-class: STANDARD_IA
  skip_cleanup: true
  local_dir: target
  acl: authenticated_read
  on:
    all_branches: true
~~~~

Here's the "bad" .travis.yml:

~~~~
# Deploy artifacts to S3
deploy:
  provider: s3
  access_key_id: <snip/>
  secret_access_key:
    secure: <snip/>
  bucket: crownpeak-builds
  upload-dir: crownpeak-s3
  storage-class: STANDARD_IA
  skip_cleanup: true
  local_dir: target
  acl: authenticated_read
  on:
    all_branches: true
~~~~

Notice the **only** difference is `upload-dir`.  Credentials (access key / secret key) are the same. S3 Bucket is the same.

A successful upload log in Travis looks like this:

~~~~
travis_time:end:2fdc37c8:start=1475154607455935740,finish=1475154620773235325,duration=13317299585
[0K
[32;1mThe command "mvn deploy --settings travis/settings.xml" exited with 0.[0m
travis_fold:start:dpl.0
[0Ktravis_time:start:0eba06a8
[0KFetching: dpl-1.8.21.gem
Fetching: dpl-1.8.21.gem (  3%)
.
<snip/>
.
Fetching: dpl-1.8.21.gem (100%)
Successfully installed dpl-1.8.21
1 gem installed

travis_time:end:0eba06a8:start=1475154620777361061,finish=1475154622187657847,duration=1410296786
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:00778a64
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Fetching: jmespath-1.3.1.gem
.
<snip/>
.
Fetching: jmespath-1.3.1.gem (100%)
Successfully installed jmespath-1.3.1
Fetching: aws-sdk-core-2.6.4.gem
Fetching: aws-sdk-core-2.6.4.gem (  1%)
.
<snip/>
.
Fetching: aws-sdk-core-2.6.4.gem (100%)
Successfully installed aws-sdk-core-2.6.4
Fetching: aws-sdk-resources-2.6.4.gem
.
<snip/>
.
Fetching: aws-sdk-resources-2.6.4.gem (100%)
Successfully installed aws-sdk-resources-2.6.4
Fetching: aws-sdk-2.6.4.gem
Fetching: aws-sdk-2.6.4.gem (100%)
Fetching: aws-sdk-2.6.4.gem (100%)
Successfully installed aws-sdk-2.6.4
4 gems installed
Fetching: mime-types-2.99.3.gem
.
<snip/>
.
Fetching: mime-types-2.99.3.gem (100%)
Successfully installed mime-types-2.99.3
1 gem installed

travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m
Logging in with Access Key: ****************VPIQ

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
uploading "classes/commons-logging.properties" with {:content_type=>"", :acl=>"authenticated-read", :storage_class=>"STANDARD_IA"}
.
<snip/>
.

travis_fold:end:dpl.3

travis_time:end:00778a64:start=1475154622193515685,finish=1475154628526809202,duration=6333293517
[0K
Done. Your build exited with 0.
~~~~

A failed upload looks like this:

~~~~
travis_time:end:0687c9ac:start=1475154993081064664,finish=1475155015543688251,duration=22462623587
[0K
[32;1mThe command "mvn deploy --settings travis/settings.xml" exited with 0.[0m
travis_fold:start:dpl.0
[0Ktravis_time:start:151a463c
[0KFetching: dpl-1.8.21.gem
Fetching: dpl-1.8.21.gem (  3%)
.
<snip/>
.
Fetching: dpl-1.8.21.gem (100%)
Successfully installed dpl-1.8.21
1 gem installed

travis_time:end:151a463c:start=1475155015548486588,finish=1475155020422483096,duration=4873996508
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:03d4803e
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Fetching: jmespath-1.3.1.gem
Fetching: jmespath-1.3.1.gem ( 11%)
.
<snip/>
.
Fetching: jmespath-1.3.1.gem (100%)
Successfully installed jmespath-1.3.1
Fetching: aws-sdk-core-2.6.4.gem
Fetching: aws-sdk-core-2.6.4.gem (  1%)
.
<snip/>
.
Fetching: aws-sdk-core-2.6.4.gem (100%)
Successfully installed aws-sdk-core-2.6.4
Fetching: aws-sdk-resources-2.6.4.gem
.
<snip/>
.
Fetching: aws-sdk-resources-2.6.4.gem (100%)
Successfully installed aws-sdk-resources-2.6.4
Fetching: aws-sdk-2.6.4.gem
Fetching: aws-sdk-2.6.4.gem (100%)
Fetching: aws-sdk-2.6.4.gem (100%)
Successfully installed aws-sdk-2.6.4
4 gems installed
Fetching: mime-types-2.99.3.gem
Fetching: mime-types-2.99.3.gem (  2%)
.
<snip/>
.
Fetching: mime-types-2.99.3.gem (100%)
Successfully installed mime-types-2.99.3
1 gem installed

travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m
Logging in with Access Key: ****************VPIQ

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
uploading "classes/crownpeak-s3.whoami.properties" with {:content_type=>"", :acl=>"authenticated-read", :storage_class=>"STANDARD_IA"}

travis_fold:end:dpl.3
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/aws-sdk-core/plugins/s3_dualstack.rb:23:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.6.4/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.6.4/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.6.4/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.6.4/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.6.4/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:56:in `block (2 levels) in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:48:in `glob'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:48:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:47:in `chdir'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:47:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider.rb:144:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider.rb:144:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/provider/s3.rb:74:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.21/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
~~~~

**Comment by adriannewby-crownpeak** [comment]
Fixed.
Lesson learned:

Once you've generated an encrypted value with `travis encrypt`, you can't take that value and then use it as-is in a separate project in a separate repository.

Apparently, the repository name forms part of the encryption key.

As soon as I regenerated the encrypted value for the AWS secret key and updated .travis.yml, everything started working.
