### ISSUE TITLE
Provider Testfairy: Invalid condition for add_boolean_param in testfairy.rb 

### ISSUE THREAD

**Issue by jparkerCAA** [travis-ci/dpl#579]
When trying to use the testfairy provider with ```notifiy: true``` we ran into what appears to be a copy-past bug on line 107 of the testfairy provider.

https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/testfairy.rb#L169

this code checks to see if the param is nil or empty however as this param accepts a boolean
the call to a non-existent empty method will throw and exception

```
/Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider/testfairy.rb:170:in `add_boolean_param': undefined method `empty?' for true:TrueClass (NoMethodError)
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider/testfairy.rb:146:in `get_params'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider/testfairy.rb:94:in `upload_app'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider/testfairy.rb:34:in `push_app'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `block in deploy'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:41:in `fold'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `deploy'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'
```

**Comment by jparkerCAA** [comment]
@BanzaiMan This one is pretty cut and dry.  If you could take a quick peek it would be helpful
