### ISSUE TITLE
Invalid unicode xml character when deploy description includes emoji (ElasticBeanstalk)

### ISSUE THREAD

**Issue by iriberri** [travis-ci/dpl#604]
### What

The error:
`Invalid unicode xml character in CreateApplicationVersionMessage.Description at index 0 (AWS::ElasticBeanstalk::Errors::InvalidParameterValue)`
is being raised when trying to deploy from a commit that includes emojis in the message using ElasticBeanstalk.

### How

If `ELASTIC_BEANSTALK_DESCRIPTION ` is not defined, pushing a commit whose message contains an emoji, such as `🚧 Some changes here` to deploy with `elasticbeanstalk` is raising the following error:

```
travis_fold:end:dpl.2
travis_fold:start:dpl.3
 [33mDeploying application [0m

travis_fold:end:dpl.3
/home/travis/.rvm/gems/ruby-2.1.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in `return_or_raise': Invalid unicode xml character in CreateApplicationVersionMessage.Description at index 0 (AWS::ElasticBeanstalk::Errors::InvalidParameterValue)
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
        from (eval):3:in `create_application_version'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/provider/elastic_beanstalk.rb:143:in `create_app_version'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/provider/elastic_beanstalk.rb:49:in `push_app'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `block in deploy'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/cli.rb:41:in `fold'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `deploy'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/cli.rb:32:in `run'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/lib/dpl/cli.rb:7:in `run'
        from /home/travis/.rvm/gems/ruby-2.1.0/gems/dpl-1.8.31/bin/dpl:5:in `<top (required)>'
        from /home/travis/.rvm/gems/ruby-2.1.0/bin/dpl:23:in `load'
        from /home/travis/.rvm/gems/ruby-2.1.0/bin/dpl:23:in `<main>'
failed to deploy
```

It looks like the description is obtained here and we're already doing some processing to make sure that it doesn't exceed 200 characters: https://github.com/travis-ci/dpl/blob/bdc795f335e23c3f470fbda89aa4a173d79dd424/lib/dpl/provider/elastic_beanstalk.rb#L132

**Comment by iriberri** [comment]
Thanks to @MariadeAnton I just noticed that this will be fixed with https://github.com/travis-ci/dpl/pull/600

**Comment by BanzaiMan** [comment]
See also #462.

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate.
