### ISSUE TITLE
Unable to deploy on bluemix/cloudfoundry

### ISSUE THREAD

**Issue by gbleu** [travis-ci/dpl#691]
Hello, I'm trying to deploy a static bundle on bluemix, it's working fine with bluemix cli `bluemix app push` but `dpl` is crashing.

Here is the output :

```
$ gem install dpl
Successfully installed dpl-1.8.43
1 gem installed
$ dpl --debug --provider=bluemixcloudfoundry --username=$BLUEMIX_USER --password=$BLUEMIX_PASSWORD --organization=$BLUEMIX_ORG --space=$BLUEMIX_SPACE --skip-ssl-validation
Installing deploy dependencies
Preparing deploy
sh: 1: test: =: unexpected operator

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
sh: 1: ./cf: not found
Deploying application
/usr/local/bundle/gems/dpl-1.8.43/lib/dpl/provider.rb:263:in `error': Failed to push app (DPL::Error)
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/provider/cloud_foundry.rb:26:in `push_app'
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/provider.rb:154:in `block in deploy'
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/provider.rb:154:in `deploy'
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/cli.rb:32:in `run'
	from /usr/local/bundle/gems/dpl-1.8.43/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.8.43/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
ERROR: Job failed: exit code 1
```

**Comment by BanzaiMan** [comment]
At least one of `$BLUEMIX_USER` `$BLUEMIX_PASSWORD` `$BLUEMIX_ORG` must be empty.

**Comment by BanzaiMan** [comment]
I spoke too soon.

It must be the case, instead, that the `cf` tool installation failed. What OS are you running this command on?

**Comment by gbleu** [comment]
I run it on a docker gitlab runner, image ruby:2.3

Setting `$TRAVIS_OS_NAME=linux` seems to solve the problem.

Thank you

**Comment by sagarrabadiya** [comment]
same issue here. can you guide how to fix or set $TRAVIS_OS_NAME=linux in gitlab ci job?

**Comment by gbleu** [comment]
In `.gitlab-ci.yml` :

```yml
variables:
    TRAVIS_OS_NAME: linux
```

**Comment by sagarrabadiya** [comment]
fixed it. Thanks for support. :)
