### ISSUE TITLE
Lambda deploy ignore hidden dot-files

### ISSUE THREAD

**Issue by codingjoe** [travis-ci/dpl#764]
https://github.com/travis-ci/dpl/blob/e6a53d8f4cb4ce76b1ce3a301af348b3f8ee8547/lib/dpl/provider/lambda.rb#L146-L151

This results in errors when you want to deploy a Python function that uses cffi.

EG:
```
key = load_pem_private_key(key, password=None, backend=default_backend())
File "/var/task/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
from cryptography.hazmat.backends.openssl.backend import backend
File "/var/task/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
from cryptography.hazmat.backends.openssl.backend import backend
File "/var/task/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
from cryptography import utils, x509
File "/var/task/cryptography/x509/__init__.py", line 8, in <module>
from cryptography.x509.base import (
File "/var/task/cryptography/x509/base.py", line 16, in <module>
from cryptography.x509.extensions import Extension, ExtensionType
File "/var/task/cryptography/x509/extensions.py", line 18, in <module>
from cryptography.hazmat.primitives import constant_time, serialization
File "/var/task/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
from cryptography.hazmat.bindings._constant_time import lib
ImportError: libffi-d78936b1.so.6.0.4: cannot open shared object file: No such file or directory
```

The file should be at:
```ZIP_ROOT/.libs_cffi_backend/libffi-d78936b1.so.6.0.4```

**Comment by BanzaiMan** [comment]
This has been fixed with 1.9.2. Use the `dot_match` option to include these dot files.

**Comment by codingjoe** [comment]
@BanzaiMan cool, but there seems to be a bug. Once I enable the flag, I get this little error.
```
Deploying application
Function lambda-lint_pycodestyle already exists, updating.
Updated configuration of function: lambda-lint_pycodestyle.
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-lambda-1.9.5/lib/dpl/provider/lambda.rb:151:in `glob': no implicit conversion of Fixnum into String (TypeError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-lambda-1.9.5/lib/dpl/provider/lambda.rb:151:in `zip_directory'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-lambda-1.9.5/lib/dpl/provider/lambda.rb:124:in `function_zip'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-lambda-1.9.5/lib/dpl/provider/lambda.rb:73:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
Sorry about that. Could you try this?

```yaml
deploy:
  provider: lambda
  edge:
    branch: lambda-dot_match
  ⋮ # rest
```

Thanks.

**Comment by codingjoe** [comment]
@BanzaiMan seems to be fine 👍

**Comment by BanzaiMan** [comment]
Will be in 1.9.6. Until the release, either

```yaml
deploy:
  provider: lambda
  edge:
    branch: lambda-dot_match
  ⋮ # rest
```
or 
```yaml
deploy:
  provider: lambda
  edge: true
  ⋮ # rest
```

is required.

**Comment by codingjoe** [comment]
Thx I switched to master, you can drop the branch.

**Comment by BanzaiMan** [comment]
1.9.6 is out.

**Comment by codingjoe** [comment]
thx, good to know 👍
