### ISSUE TITLE
Github Pages deployment simply stopped working

### ISSUE THREAD

**Issue by theomessin** [travis-ci/dpl#767]
Tried deleting all repository caches as well. Everything worked fine, tried to rebuild the same repo (ie. code) and then nothing worked fine :cry:  

```
Deploying application
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `mkdir': File exists @ dir_s_mkdir - /tmp/d20180308-5759-1rawmx3/work (Errno::EEXIST)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `github_pull_or_init'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:196:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:191:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

https://github.com/travis-ci/travis-ci/issues/9312

**Comment by BanzaiMan** [comment]
Closing as a duplicate.

**Comment by nebulousdog** [comment]
@BanzaiMan do you know which one was original issue? I'd like to find, because I have same issue atm.

**Comment by maximelebastard** [comment]
I'm having this issue as well
