### ISSUE TITLE
 "The system cannot find the path specified" error on Windows

### ISSUE THREAD

**Issue by DanTup** [travis-ci/dpl#808]
When I run `dpl` on my Windows PC, I get "The system cannot find the path specified" errors. Happens in both cmd and PowerShell.

```
PS C:\Users\danny\AppData\Local\Temp\dpl\Dart-Code> dpl --provider="s3" --access-key-id="AAAAAAAAAAAAAAAAAAAAA" --secret-access-key="AAAAAAAAAAAAAAAAA
AAAA" --bucket="test-results.dartcode.org" --skip_cleanup="true" --local-dir="logs" --upload-dir="logs" --acl="public_read"
Installing deploy dependencies
The system cannot find the path specified.
The system cannot find the path specified.
Preparing deploy
Logging in with Access Key: ****************AAAA
Deploying application
Beginning upload of 1 files with 5 threads.
#<Thread:0x000000000e0f5510@M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-s3-1.9.6/lib/dpl/provider/s3.rb:82 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-s3-1.9.6/lib/dpl/provider/s3.rb:91:in `block (2 levels) in upload_multithreaded'
        2: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-s3-1.9.6/lib/dpl/provider/s3.rb:124:in `content_data_for'
        1: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-1.9.6/lib/dpl/provider.rb:278:in `encoding_for'
M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-1.9.6/lib/dpl/provider.rb:278:in ``': No such file or directory - file 'test_log.txt' (Errno::ENOENT)
Traceback (most recent call last):
        3: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-s3-1.9.6/lib/dpl/provider/s3.rb:91:in `block (2 levels) in upload_multithreaded'
        2: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-s3-1.9.6/lib/dpl/provider/s3.rb:124:in `content_data_for'
        1: from M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-1.9.6/lib/dpl/provider.rb:278:in `encoding_for'
M:/Apps/Ruby/lib/ruby/gems/2.5.0/gems/dpl-1.9.6/lib/dpl/provider.rb:278:in ``': No such file or directory - file 'test_log.txt' (Errno::ENOENT)
PS C:\Users\danny\AppData\Local\Temp\dpl\Dart-Code>
```

**Comment by DanTup** [comment]
It's caused by the call to `file '#{path}'` which fails on Windows (there's no `file).

Is dpl expected to work on Windows?

**Comment by BanzaiMan** [comment]
Ah, I see the issue now. Indeed, your analysis appears correct.

Up to this point, we have not considered execution on Windows, so there are many places where `dpl` would fail to run on Windows.

**Comment by DanTup** [comment]
It actually seems to upload fine (and even sets the content types) despite this:

```
dpl --provider=s3 --bucket="test-results.dartcode.org" --skip_cleanup="true" --local-dir=".test_results" --upload-dir="logs" --acl=public_read

The system cannot find the path specified.
The system cannot find the path specified.
Logging in with Access Key: ****************ZSKQ
Beginning upload of 15 files with 5 threads.
uploading "not_activated_flutter_create_stable_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "not_activated_flutter_create_stable_insiders.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_upgraded_stable_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "not_activated_flutter_create_dev_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_upgraded_stable_insiders.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_upgraded_dev_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_stable_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_stable_insiders.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "multi_root_dev_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "flutter_only_stable_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "flutter_only_stable_insiders.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "flutter_only_dev_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "dart_only_stable_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "dart_only_stable_insiders.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
uploading "dart_only_dev_stable.xml" with {:content_type=>"application/xml", :acl=>"public-read"}
Installing deploy dependencies
Preparing deploy
```

I don't know if the two errors mean there are two missing files, but the counts all match up with the Linux/MAC ones. As far as I can tell, the error isn't fatal (it's just rather confusing).

**Comment by BanzaiMan** [comment]
The failure means that we couldn't figure out the encoding data for the files you are uploading. The execution continues, and MIME types are found for your `.xml` files, so everything appears fine.
