### ISSUE TITLE
Unable to Deploy to Heroku: 'cannot load such file -- dpl/provider/heroku (LoadError)'

### ISSUE THREAD

**Issue by davydany** [travis-ci/dpl#819]
I installed `dpl` using `bundle install`. Then, I am using the `heroku` provider for DPL to deploy my project. I am receiving this error:

Here are the contents of my Gemfile:

```
source 'https://rubygems.org'
gem 'dpl', '~> 1.9'
```

Here is the output of `bundle install`

```
╰─$ bundle install
Using bundler 1.16.1
Using dpl 1.9.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Here is how I am using the command: 

```
╰─$ bundle exec dpl --provider=heroku --api-key=`heroku auth:token`
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.2
Successfully installed rendezvous-0.1.2
Successfully installed netrc-0.11.0
Successfully installed dpl-heroku-1.9.6
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for multipart-post-2.0.0
Parsing documentation for faraday-0.15.2
Parsing documentation for rendezvous-0.1.2
Parsing documentation for netrc-0.11.0
Parsing documentation for dpl-heroku-1.9.6
Done installing documentation for multipart-post, faraday, rendezvous, netrc, dpl-heroku after 1 seconds
5 gems installed
/Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/provider.rb:92:in `require': cannot load such file -- dpl/provider/heroku (LoadError)
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/provider.rb:92:in `rescue in block in new'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/provider.rb:67:in `block in new'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/provider.rb:66:in `new'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/cli.rb:31:in `run'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/davydany/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

This was working literally 5 hours ago, but suddenly not working anymore.

**Comment by granicus-pigeon** [comment]
For future reference to people stumbling across this, I found that adding `dpl-heroku` to the gemfile instead of `dpl` made this work.

**Comment by carrchr** [comment]
praise you @granicus-pigeon 🙏

**Comment by daviddossantos** [comment]
Hey guys, see the documention in that link https://github.com/travis-ci/dpl#heroku-api, it worked for me

**Comment by daviddossantos** [comment]
if the error below occurs, install the `bundler` dependency
![image](https://user-images.githubusercontent.com/37313667/97451988-0aba8100-1913-11eb-9c79-c83d284c77ab.png)
![image](https://user-images.githubusercontent.com/37313667/97452190-3dfd1000-1913-11eb-9e06-08e0e5afe159.png)
