### ISSUE TITLE
GitHub Releases: overwrite param is not working with some characters in filenames

### ISSUE THREAD

**Issue by slodki** [travis-ci/dpl#821]
GitHub auto-renames Releases assets uploaded from webpage or travis dpl script removing and replacing some characters, changing filename length etc.

dpl script is unable to detect such filenames now and overwrite them:
https://github.com/travis-ci/dpl/blob/26db7943acd693bf22504d28fdf287375288f896/lib/dpl/provider/releases.rb#L114
Filename prepared to upload does not exist on GH side, so it's not renamed, but GH returns error while uploading because file with the same **renamed filename** exists.

**[Example log](https://travis-ci.org/slodki/travis-tests/builds/387033161):**
```
$ echo Local filenames && ls *.txt
Local filenames
a5_ !#$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~.txt
a5_a a\!a#a$a%a&a'a\(a\)a+a,a-a.a0123456789a;a=a@aABCDEFGHIJKLMNOPQRSTUVWXYZa[a]a^a_a\`abcdefghijklmnopqrstuvwxyza{a}a~a.txt
a5_ð_æ_©_ŋ.txt
a5.txt
a5_żółw.txt
[...]
Filenames at GitHub Releases:
  "name": "same",
      "name": "a5.txt",
      "name": "a5_.-.0123456789.ABCDEFGHIJKLMNOPQRSTUVWXYZ._.abcdefghijklmnopqrstuvwxyz.txt",
      "name": "a5_a.a.a.a.a.a.a.a.a.a.a.a-a.a0123456789a.a.a.aABCDEFGHIJKLMNOPQRSTUVWXYZa.a.a.a_a.abcdefghijklmnopqrstuvwxyza.a.a.a.txt",
      "name": "a5_d_ae_._ng.txt",
[...]
Logged in as 
Deploying to repo: slodki/travis-tests
Current tag is: same
a5.txt already exists, overwriting.
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/slodki/travis-tests/releases/11291552/assets?name=a5_%C3%B0_%C3%A6_%C2%A9_%C5%8B.txt: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: ReleaseAsset
  code: already_exists
  field: name // See: https://developer.github.com/v3
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
[...]
```
As you can see simple filenames like *a5.txt* are correctly overwritten, but filenames with special characters (replaced with dot by GitHub) or unicode characters (casefolded?) returns *already_exists* error response.

**Possible solution:**
Implement the same renaming rules in dpl script and apply them to filenames **before** GH API calls. I cannot find GitHub specification of renaming rules but this can be reverse-engineered (see examples above).

**Comment by slodki** [comment]
This error is [raised with simple filenames](https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/410069132#L4078) (like `mmex_1.4.0-alpha.4_amd64.snap`) too:
```
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.2
Successfully installed public_suffix-3.0.2
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
Successfully installed mime-types-2.99.3
Successfully installed dpl-releases-1.9.8
8 gems installed
Logged in as 
Deploying to repo: moneymanagerex/moneymanagerex
Current tag is: nightly
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/moneymanagerex/moneymanagerex/releases/12046484/assets?name=mmex_1.4.0-alpha.4_amd64.snap: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: ReleaseAsset
  code: already_exists
  field: name // See: https://developer.github.com/v3
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.8/lib/dpl/provider/releases.rb:144:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.8/lib/dpl/provider/releases.rb:125:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.8/lib/dpl/provider/releases.rb:115:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.8/lib/dpl/provider/releases.rb:115:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/provider.rb:195:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/provider.rb:195:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

**Comment by slodki** [comment]
I will retest this after #851

**Comment by slodki** [comment]
still not working

**Comment by svenfuchs** [comment]
i have uploaded these files:

```
a5_ !#$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~.txt
a5_a a\!a#a$a%a&a'a\(a\)a+a,a-a.a0123456789a;a=a@aABCDEFGHIJKLMNOPQRSTUVWXYZa[a]a^a_a\`abcdefghijklmnopqrstuvwxyza{a}a~a.txt
a5_ð_æ_©_ŋ.txt
a5.txt
a5_żółw.txt
```

they get listed as:

```
a5_
a5_a
a5_d_ae_._ng.txt
a5_zolw.txt
```

so, it looks like filenames are split at spaces, and only the first part remains. special chars seem to be transliterated somehow.

**Comment by svenfuchs** [comment]
really wondering what GitHub does here ...

```
a00_!a.txt
a01_#a.txt
a02_$a.txt
a03_%a.txt
a04_&a.txt
a05_'a.txt
a06_(a.txt
a07_)a.txt
a08_+a.txt
a09_,a.txt
a10_-a.txt
a11_.a.txt
a12_;a.txt
a13_=a.txt
a14_@a.txt
a15_[a.txt
a16_\a.txt
a17_]a.txt
a18_^a.txt
a19__a.txt
a20_`a.txt
a21_{a.txt
a22_}a.txt
a23_~a.txt
```

lists:


```
a00_.a.txt
a01_.a.txt
a02_.a.txt
a03_.a.txt
a04_.a.txt
a05_.a.txt
a06_.a.txt
a07_.a.txt
a08_+a.txt
a09_.a.txt
a10_-a.txt
a11_.a.txt
a12_.a.txt
a13_.a.txt
a14_@a.txt
a15_.a.txt
a16_.a.txt
a17_.a.txt
a18_.a.txt
a19__a.txt
a20_.a.txt
a21_.a.txt
a22_.a.txt
a23_.a.txt
```

**Comment by svenfuchs** [comment]
i think this should fix the issue: https://github.com/travis-ci/dpl/pull/1131/files ... or at least a large part of it

**Comment by svenfuchs** [comment]
i have merged https://github.com/travis-ci/dpl/pull/1131 after some more testing.

@slodki if you want to give this a go, please use `branch: master` as this is not released, yet:

```yaml
deploy:
- provider: releases
  edge:
    branch: master
```

i will close this issue here for the time being. please feel free to re-open it if needed.
