### ISSUE TITLE
[provider: snap] "Unable to locate package snapd" error while installing deploy dependencies 

### ISSUE THREAD

**Issue by slodki** [travis-ci/dpl#845]
Travis config:
```yaml
deploy:
- provider: snap
  snap: mmex
  channel: edge
  skip_cleanup: true
  on:
    tags: true
    conndition: $OS = snap && ${#SNAP_TOKEN} != 0
```
Travis [log](https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/407817705):
```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.8
1 gem installed

Installing deploy dependencies
Successfully installed dpl-snap-1.9.8
1 gem installed
E: Unable to locate package snapd
sudo: snap: command not found
Attemping to login

Preparing deploy
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/open3.rb:193:in `spawn': No such file or directory - snapcraft (Errno::ENOENT)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/open3.rb:93:in `popen3'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/open3.rb:252:in `capture3'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-snap-1.9.8/lib/dpl/provider/snap.rb:32:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/provider.rb:183:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/provider.rb:182:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

@kyrofa: `snapd` and `snapcraft` commands (dpl-snap dependencies) are not installed IMHO.

**Comment by kyrofa** [comment]
@slodki interesting, snapd is a [package in Trusty](https://packages.ubuntu.com/trusty-updates/snapd) and Xenial. Did you change any of the available deb repos before DPL ran?

**Comment by slodki** [comment]
No, [this](https://github.com/moneymanagerex/moneymanagerex/blob/master/.travis.yml) is clean Travis image with all tasks running inside snapcore/snapcraft docker image.

**Comment by slodki** [comment]
More tests with Travis trusty, sudo enabled cpp image.
`sudo apt install snapd` finds snapd package but requires `apt update` before.
Installing snapd is very long process - it takes about 150 seconds!
```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  amd64-microcode intel-microcode iucode-tool libpam-systemd libseccomp2
  libsystemd-daemon0 libsystemd-journal0 libsystemd-login0
  linux-generic-lts-xenial linux-headers-4.4.0-131
  linux-headers-4.4.0-131-generic linux-headers-generic-lts-xenial
  linux-image-4.4.0-131-generic linux-image-extra-4.4.0-131-generic
  linux-image-generic-lts-xenial squashfs-tools systemd systemd-services
Suggested packages:
  fdutils linux-lts-xenial-tools systemd-ui cgmanager
Recommended packages:
  initramfs-tools thermald
The following NEW packages will be installed:
  amd64-microcode intel-microcode iucode-tool libseccomp2
  linux-generic-lts-xenial linux-headers-4.4.0-131
  linux-headers-4.4.0-131-generic linux-headers-generic-lts-xenial
  linux-image-4.4.0-131-generic linux-image-extra-4.4.0-131-generic snapd
  squashfs-tools systemd
The following packages will be upgraded:
  libpam-systemd libsystemd-daemon0 libsystemd-journal0 libsystemd-login0
  linux-image-generic-lts-xenial systemd-services
6 upgraded, 13 newly installed, 0 to remove and 226 not upgraded.
Need to get 85.4 MB of archives.
After this operation, 401 MB of additional disk space will be used.
```
It will install new linux kernel, generate new initrd image and update grub. It may be worth to update Travis image to not waste time installing dpl later?

Then snapcraft can be installed with `sudo snap install snapcraft --classic`

```
sudo apt update
sudo apt install snapd
sudo snap install snapcraft --classic
```
Above commands are working in `before_script`. I don't know why `dpl` have problems with it? Maybe `apt update` is not executed? Or `dpl` script has no access to apt configuration/su privileges?

**Comment by kyrofa** [comment]
Yeah it sounds like DPL should be running `apt update` as part of its `apt_get` function somewhere (perhaps on first run). The snap provider [just hooks into it](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/snap.rb#L21), I'm not really sure this is something we can do on a provider level.

**Comment by slodki** [comment]
unstale

**Comment by BanzaiMan** [comment]
Please test a potential fix with
```yaml
deploy:
  provider: snap
  edge:
    branch: apt-get-update
  ⋮ # rest
```

**Comment by BanzaiMan** [comment]
@slodki @kyrofa Has either of you had a chance to test the proposed fix above?

**Comment by slodki** [comment]
No, I've moved snap build process from Travis to build.snapcraft.io
