### ISSUE TITLE
puppetforge deploy provider is broken since puppet 6.0 release

### ISSUE THREAD

**Issue by myMarck** [travis-ci/dpl#870]
In my travis file I have the following

deploy:
  provider: puppetforge
  user: someone
  password:
    secure: "blablabla"
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"

When the code is executed on travis the log contains

rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.10.1.gem (100%)
Successfully installed dpl-1.10.1
1 gem installed
dpl.1
Installing deploy dependencies
Fetching: facter-2.5.1.gem (100%)
Successfully installed facter-2.5.1
Fetching: hiera-3.4.5.gem (100%)
Successfully installed hiera-3.4.5
Fetching: semantic_puppet-1.0.2.gem (100%)
Successfully installed semantic_puppet-1.0.2
Fetching: fast_gettext-1.1.2.gem (100%)
Successfully installed fast_gettext-1.1.2
Fetching: locale-2.1.2.gem (100%)
Successfully installed locale-2.1.2
Fetching: multi_json-1.13.1.gem (100%)
Successfully installed multi_json-1.13.1
Fetching: httpclient-2.8.3.gem (100%)
Successfully installed httpclient-2.8.3
Fetching: hocon-1.2.5.gem (100%)
Successfully installed hocon-1.2.5
Fetching: puppet-resource_api-1.5.0.gem (100%)
Successfully installed puppet-resource_api-1.5.0
Fetching: puppet-6.0.0.gem (100%)
ERROR:  Error installing dpl-puppet_forge:
	The last version of puppet (>= 0) to support your Ruby & RubyGems was 5.5.6. Try installing it with `gem install puppet -v 5.5.6` and then running the current command again
	puppet requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- dpl/provider/puppet_forge (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/provider.rb:94:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/provider.rb:69:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/provider.rb:68:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.10.1/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy

**Comment by BanzaiMan** [comment]
Looks like we'll have to pin the puppetforge version.

**Comment by BanzaiMan** [comment]
You can also install `puppet` 5.5.6 in `before_deploy`:

```yaml
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install puppet -v 5.5.6
⋮
```
