### ISSUE TITLE
deploy fails due to permission problems

### ISSUE THREAD

**Issue by jleni** [travis-ci/dpl#899]
Since yesterday, there are problems when deploying to pypi.
I have tried to preinstall 38.4.0 so there is no need for the travis deploy script to make changes..

I have also tried to go for a workaround:
    - sudo chmod -R 0777 /usr/lib/python2.7/
    - sudo chmod -R 0777 /usr/local/lib
but that does not seem to work either.
Has anyone seen this problem before?

Here is a log to a broken build:
https://travis-ci.org/theQRL/qryptonight/jobs/333186291

> Collecting setuptools
>  Downloading setuptools-38.4.0-py2.py3-none-any.whl (489kB)
>    100% |████████████████████████████████| 491kB 1.9MB/s 

....

>   Found existing installation: setuptools 38.2.4
>     Uninstalling setuptools-38.2.4:
> Exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 778, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
>     renames(path, new_path)
>   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
>     shutil.move(old, new)
>   File "/usr/lib/python2.7/shutil.py", line 303, in move
>     os.unlink(src)
> OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325.
