### ISSUE TITLE
Chef supermarket deploy fails with uninitialized constant

### ISSUE THREAD

**Issue by majormoses** [travis-ci/dpl#969]
Here is the error message:
```
/home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-chef_supermarket-1.10.7/lib/dpl/provider/chef_supermarket.rb:36:in `check_app': uninitialized constant Chef::CookbookUploader (NameError)
Did you mean?  Chef::CookbookLoader
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/lib/dpl/provider.rb:188:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/lib/dpl/provider.rb:186:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/dpl-1.10.7/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.3/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.3/bin/dpl:23:in `<main>'
```

Link to error: https://travis-ci.org/Netuitive/chef-netuitive/jobs/506030147#L1200-L1209

We are an EOL version of chef here but I went back and I see the class being defined here: https://github.com/chef/chef/blob/v12.9.42/lib/chef/cookbook_uploader.rb#L15

Taking a quick look I don't see what the issue is but maybe when I have some more time I can sit down and figure this out

**Comment by BanzaiMan** [comment]
This is curious. RubyGems is not installing the runtime dependency `chef` https://travis-ci.org/Netuitive/chef-netuitive/jobs/506030147#L1193

This is clearly indicated in https://rubygems.org/gems/dpl-chef_supermarket, and it happens if I do that. https://travis-ci.org/BanzaiMan/travis_production_test/builds/509441953#L528

I am not sure why your build does not.

**Comment by iamjohnnym** [comment]
👋 Hello! I also appear to be experiencing this issue.  I've since moved over to using `stove` but I'd prefer to use this method since its more native to Travis and a bit cleaner overall.

Here's the job: https://travis-ci.org/socrata-cookbooks/bastion/jobs/511668424#L969
Here's the `.travis.yml`: https://github.com/socrata-cookbooks/bastion/blob/9f2349f8fb29498f335e5951797cd5f573ad2376/.travis.yml#L44

My first thought goes to the fact that I'm doing everything with `chef exec ${FOO}` and the way this `dpl` is configured might not play well with it.  However, that's just a thought.  Unfortunately, I don't currently have the bandwidth to test different theories but when I do get some, I plan on creating a completely separate repo that can build in a couple minutes vs this current cookbook.

**Comment by BanzaiMan** [comment]
Please test #978 with:

```yaml
deploy:
  provider: chef_supermarket
  edge:
    branch: req-chef-cookbook_uploader
  ⋮ # rest
```

Thanks.

**Comment by iamjohnnym** [comment]
@BanzaiMan negative ghost rider.  

https://travis-ci.org/socrata-cookbooks/bastion/jobs/511745053#L1030

```bash
/home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/cookbook_uploader.rb:43:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/cookbook_uploader.rb:43:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-chef_supermarket-1.10.8/lib/dpl/provider/chef_supermarket.rb:40:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-chef_supermarket-1.10.8/lib/dpl/provider/chef_supermarket.rb:40:in `check_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:188:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:186:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
So, I have some bad news for you. Looking at the history of this provider's implementation, it was never fully tested. (This was before a lot of the current testing machinery was put in place, and we therefore had very little oversight into what gets into the release.)

We might have some bumps as I polish up this code. I apologize and thank you for your patience in advance.

Now. I pushed a new commit to this branch. Could you restart the job and report the result? Thanks!

**Comment by iamjohnnym** [comment]
@BanzaiMan Ha.  That's excellent.  Such happens with tech though so no worries.

I've ran it again but no dice. https://travis-ci.org/socrata-cookbooks/bastion/jobs/511745053#L1030

```bash
/home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-chef_supermarket-1.10.8/lib/dpl/provider/chef_supermarket.rb:40:in `check_app': undefined method `validate_cookbooks' for #<Chef::CookbookLoader:0x0000000346ee68> (NoMethodError)
Did you mean?  load_cookbooks
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:188:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:186:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```
I added some comments on your PR.  It looks like the wrong object is being instantiated here.  We've got `Chef::CookbookLoader`, which lacks `validate_cookbooks`.  The `Chef::CookbookUploader` appears to have the proper method though.

**Comment by BanzaiMan** [comment]
We'll continue discussion on how to bring this provider to life in #978.

**Comment by iamjohnnym** [comment]
I think we're close.

https://travis-ci.org/socrata-cookbooks/bastion/jobs/511745053#L1030

```bash
/home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http/authenticator.rb:95:in `initialize': password must be at least 4 bytes (OpenSSL::OpenSSLError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http/authenticator.rb:95:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http/authenticator.rb:95:in `load_signing_key'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http/authenticator.rb:42:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http.rb:98:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http.rb:98:in `block in initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http.rb:97:in `each'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/http.rb:97:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/server_api.rb:40:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/cookbook_uploader.rb:43:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/chef-14.11.21/lib/chef/cookbook_uploader.rb:43:in `initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-chef_supermarket-1.10.8/lib/dpl/provider/chef_supermarket.rb:40:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-chef_supermarket-1.10.8/lib/dpl/provider/chef_supermarket.rb:40:in `check_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:188:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:186:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

When I get into the office, I can help dig in more.

**Comment by BanzaiMan** [comment]
@iamjohnnym Let's keep the comments on the PR in the PR.
