### ISSUE TITLE
Heroku deployment stoped working with release of dpl-heroku-1.10.9

### ISSUE THREAD

**Issue by ruzicka** [travis-ci/dpl#997]
I was using dpl to deploy code on heroku. It was working fine until installed deploy dependency changed from `dpl-heroku-1.10.8` to `dpl-heroku-1.10.9`. Then it end up with these errors:

```
Installing deploy dependencies
Successfully installed rendezvous-0.1.3
Successfully installed netrc-0.11.0
Successfully installed dpl-heroku-1.10.9
3 gems installed
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- faraday (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/dpl-heroku-1.10.9/lib/dpl/provider/heroku.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:68:in `block in new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:67:in `new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:31:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dpl/provider/heroku (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:68:in `block in new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:67:in `new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:31:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dpl/provider/heroku (LoadError)
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:73:in `block in new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/provider.rb:67:in `new'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:31:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.10.9/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
```

**Comment by Roogerr** [comment]
same

**Comment by BanzaiMan** [comment]
Sorry for the troubles.

I'll look at this again.

In the mean time, you can try:

```yaml
deploy:
  provider: heroku
  edge:
    branch: 1.10.8
  ⋮
```

**Comment by BanzaiMan** [comment]
I've pushed 1.10.10 (https://rubygems.org/gems/dpl-heroku/versions/1.10.10) which reinstates "faraday" to runtime dependencies. This should resolve the issue. Please try again, and report the results.

Thank you, and I apologize for this oversight in 1.10.9.

**Comment by BanzaiMan** [comment]
Thanks for the reports. I'm closing this now.

**Comment by LoveConnie** [comment]
default
